name: Bug report
description: Report a way in which WorldEditCUI is not working as intended
labels: ['bug']

body:
- type: markdown
  attributes:
    value: |
      Please note that this is only for bugs, help with installation or other types of support should
      be taken to the Discord Guild instead.

- type: input
  attributes:
    label: WorldEditCUI Version
    description: The full version of WorldEditCUI
    placeholder: e.g. 1.16.5+0.2
  validations:
    required: true

- type: input
  attributes:
    label: Fabric Version
    description: |
      Please ensure you are running up-to-date software before making a bug report.
      Old versions or hybrids will receive little to no support.
    placeholder: e.g. Fabric 0.9.0
  validations:
    required: true

- type: input
  attributes:
    label: Fabric API Version
    description: Please ensure you are running up-to-date software before making a bug report.
    placeholder: e.g. Fabric API 0.43.0+1.17
  validations:
    required: true

- type: checkboxes
  id: confirmations
  attributes:
    label: Confirmations
    description: Please confirm the following before submitting the bug. Your report will be closed if you are running old software.
    options:
      - label: I am using the most recent Minecraft release.
        required: true
      - label: I am using a version of WorldEditCUI compatible with my Minecraft version.
        required: true
      - label: I am using the latest or recommended version of my platform software.
        required: true

- type: textarea
  attributes:
    label: Bug Description
    description: A clear and concise description of what the bug is.
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected Behavior
    description: The behavior that you expected, instead of the bugged behavior that occurs.
  validations:
    required: true

- type: textarea
  attributes:
    label: Reproduction Steps
    description: Steps to reproduce the behavior.
    value: |
      1. ...
      2. ...
  validations:
    required: true

- type: textarea
  attributes:
    label: Anything Else?
    description: Add any additional context you can provide below.

